# Example Site settings

google_analytics: G-DW5JPXQ9G7

header_pages:
 - index.md
 - schedule.md
footer: ''

style: hacker # dark (default) or light
# listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
